### ISSUE TITLE
Swipe error after upgrading to version 16.0 from 14.2

### ISSUE THREAD

**Issue by emclab** [wcandillon/react-native-redash#435]
The swipe component in RN 0.64 throws error on android emulator after upgrading `react-native-redash` from 14.2 to 16.0:

       ERROR  TypeError: (0, _$$_REQUIRE(_dependencyMap[8], "react-native-redash").useValue) is not a function. (In '(0, _$$_REQUIRE(_dependencyMap[8], "react-native-redash").useValue)(initIndex)', '(0, _$$_REQUIRE(_dependencyMap[8], "react-native-redash").useValue)' is undefined)

This error is located at:
    in Swipe (at SceneView.tsx:122)
    in StaticContainer
    in EnsureSingleNavigator (at SceneView.tsx:114)
    in SceneView (at useDescriptors.tsx:153)
    in RCTView (at View.js:34)
    in View (at CardContainer.tsx:245)
    in RCTView (at View.js:34)
    in View (at CardContainer.tsx:244)
    in RCTView (at View.js:34)
    in View (at CardSheet.tsx:33)
    in CardSheet (at Card.tsx:573)
    in RCTView (at View.js:34)
    in View (at createAnimatedComponent.js:217)
    in AnimatedComponent (at createAnimatedComponent.js:278)
    in AnimatedComponentWrapper (at Card.tsx:555)
    in PanGestureHandler (at GestureHandlerNative.tsx:13)
    in PanGestureHandler (at Card.tsx:549)
    in RCTView (at View.js:34)
    in View (at createAnimatedComponent.js:217)
    in AnimatedComponent (at createAnimatedComponent.js:278)
    in AnimatedComponentWrapper (at Card.tsx:544)
    in RCTView (at View.js:34)
    in View (at Card.tsx:538)
    in Card (at CardContainer.tsx:206)
    in CardContainer (at CardStack.tsx:623)
    in RNSScreen (at createAnimatedComponent.js:217)
    in AnimatedComponent (at createAnimatedComponent.js:278)
    in AnimatedComponentWrapper (at src/index.native.tsx:120)
    in Screen (at Screens.tsx:74)
    in MaybeScreen (at CardStack.tsx:616)
    in RNSScreenContainer (at src/index.native.tsx:145)
    in ScreenContainer (at Screens.tsx:50)
    in MaybeScreenContainer (at CardStack.tsx:498)
    in CardStack (at StackView.tsx:462)
    in KeyboardManager (at StackView.tsx:458)
    in SafeAreaProviderCompat (at StackView.tsx:455)
    in RCTView (at View.js:34)
    in View (at GestureHandlerRootView.android.tsx:21)
    in GestureHandlerRootView (at StackView.tsx:454)
    in StackView (at createStackNavigator.tsx:87)
    in StackNavigator (at AppScreen.js:140)
    in AppScreen (at SceneView.tsx:122)
    in StaticContainer
    in EnsureSingleNavigator (at SceneView.tsx:114)
    in SceneView (at useDescriptors.tsx:153)
    in RCTView (at View.js:34)
    in View (at CardContainer.tsx:245)
    in RCTView (at View.js:34)
    in View (at CardContainer.tsx:244)
    in RCTView (at View.js:34)
    in View (at CardSheet.tsx:33)
    in CardSheet (at Card.tsx:573)
    in RCTView (at View.js:34)
    in View (at createAnimatedComponent.js:217)
    in AnimatedComponent (at createAnimatedComponent.js:278)
    in AnimatedComponentWrapper (at Card.tsx:555)
    in PanGestureHandler (at GestureHandlerNative.tsx:13)
    in PanGestureHandler (at Card.tsx:549)
    in RCTView (at View.js:34)
    in View (at createAnimatedComponent.js:217)
    in AnimatedComponent (at createA

The `react-native-reanimated` is upgraded from v1 to v2.1 and gesture handler from 1.7 to 1.10 as well. 

Here is the code:

      import Animated, {
  add,
  and,
  clockRunning,
  block,
  cond,
  divide,
  eq,
  floor,
  multiply,
  neq,
  not,
  onChange,
  set,
  sub,
  useCode,
  call,
  Value,
    } from "react-native-reanimated";
    import {
  clamp,
  snapPoint,
  timing,
  useClock,
  usePanGestureHandler,
  usePinchGestureHandler,
  useValue,
  vec,
    } from "react-native-redash";
    import {
  PanGestureHandler,
  PinchGestureHandler,
  State,
  TouchableOpacity,
    } from "react-native-gesture-handler";
    import { CANVAS, usePinch } from "./swipeUtil";

Many thanks.
